apiVersion: v1
kind: Service    #表明是Kubernetes Service
metadata:
  name: mysql    #Service的全局唯一名称;Service 的服务名
spec:
  ports:
    - port: 3306  #Service提供服务的端口号
  selector:
    app: mysql    #service对应的Pod拥有这里定义的标签; 确定了哪些Pod副本(实例)对应到本服务