apiVersion: v1
kind: ReplicationController     #表明此资源对象的内型，"ReplicationController表明这是一个RC"
metadata:
  name: mysql                   #RC的名称，全局唯一
spec:                           #spec是RC的相关属性定义
  replicas: 1                   #副本期待数量
  selector:                     #是RC的Pod标签选择器，监控和管理拥有这些标签的Pod实例，确保当前集群上始终有且仅有replicas个Pod实例在运行，这里设置的replicas=1表明只能运行一个Mysql Pod实例，当集群中运行的Pod数量小于replicas时，RC会根据spec.template一节中定义的Pod模板来生成一个新的Pod实例，spec.template.metadata.labels指定了该Pod的标签，，需要注意的是这里的labels必须匹配之前的spec.selector，否则此RC每次创建了一个无法匹配Label的Pod，就会不停地尝试创建新的Pod.
    app: mysql                  #符合目标的Pod拥有此标签
  template:                     #根据此模板创建Pod的副本（实例）
    metadata:
      labels:
        app: mysql              #Pod副本拥有的标签，对应RC的Selector
    spec:
      containers:               #Pod内容器的定义部分
        - name: mysql             #容器的名称
          image: mysql            #容器的镜像
          ports:                  #容器暴露的端口
            - containerPort: 3306
          env:                    #注入到容器内的环境变量
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"