apiVersion: v1
kind: Service
metadata:
  name: myweb
spec:
  type: NodePort       #表明此Service开启了NodePort方式的外网访问模式
  ports:
    - port: 8080
      nodePort: 30001  #在集群之外，可以通过30001这个端口访问myweb,对应到8080的虚端口上。
  selector:
    app: myweb